apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
        - image: nginx
          name: nginx
